config/routes.rb
Rails.application.routes.draw do
  resources :laptops
  root 'home#index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/laptop.rb
class Laptop < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  
end

app/controllers/laptops_controller.rb
class LaptopsController < ApplicationController
  before_action :set_laptop, only: %i[ show edit update destroy ]

  # GET /laptops or /laptops.json
  def index
    @laptops = Laptop.all
  end

  # GET /laptops/1 or /laptops/1.json
  def show
  end

  # GET /laptops/new
  def new
    @laptop = Laptop.new
  end

  # GET /laptops/1/edit
  def edit
  end

  # POST /laptops or /laptops.json
  def create
    @laptop = Laptop.new(laptop_params)

    respond_to do |format|
      if @laptop.save
        format.html { redirect_to laptop_url(@laptop), notice: "Laptop was successfully created." }
        format.json { render :show, status: :created, location: @laptop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @laptop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /laptops/1 or /laptops/1.json
  def update
    respond_to do |format|
      if @laptop.update(laptop_params)
        format.html { redirect_to laptop_url(@laptop), notice: "Laptop was successfully updated." }
        format.json { render :show, status: :ok, location: @laptop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @laptop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /laptops/1 or /laptops/1.json
  def destroy
    @laptop.destroy

    respond_to do |format|
      format.html { redirect_to laptops_url, notice: "Laptop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_laptop
      @laptop = Laptop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def laptop_params
      params.require(:laptop).permit(:brand, :model, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/laptops_helper.rb
module LaptopsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <%= link_to 'Techmarket App', root_path, class:"navbar-brand" %>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">        
            <li class="nav-item">
                <%= link_to "Laptops", laptops_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
                <%= link_to "About us", home_about_path, class:"nav-link"%>
            </li>
        </ul>
        </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1> About us</h1>

app/views/home/index.html.erb
<h1>Hello World!</h1>
<h4>This is my first ruby on rails Webpage</h4>
<br/>
<h5>To do list</h5>
<p>Mini game with ruby</p>
<p>Login System</p>
<p>Mobile phones database</p>
<p>Shopping cart</p>
<p>Upload to heroku</p>
<p>Frontend update</p>

app/views/laptops/_form.html.erb
<%= form_with(model: laptop) do |form| %>
  <% if laptop.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(laptop.errors.count, "error") %> prohibited this laptop from being saved:</h2>

      <ul>
        <% laptop.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="d-flex align-items-center justify-content-center">
    <div>
     <div class="field form-group">
        <%= form.label :brand, style: "display: block" %>
        <%= form.text_field :brand, class:"form-control" %>
      </div>

      <div class="field form-group">
        <%= form.label :model, style: "display: block" %>
        <%= form.text_field :model, class:"form-control" %>
      </div >

      <div class="field form-group">
        <%= form.label :price, style: "display: block" %>
        <%= form.text_field :price, class:"form-control" %>
      </div>
      <br/>
      <div class="d-flex align-items-center justify-content-center">
        <%= form.submit :Submit,class: 'btn btn-success' %>
      </div>
    </div>
  </div>
<% end %>

app/views/laptops/_laptop.html.erb
<tr id="<%= dom_id laptop %>" class="align-middle">
  <td>
    <%= laptop.brand %>
  </td>

  <td>
    <%= laptop.model %>
  </td>

  <td>
    <%= laptop.price %>
  </td>
  
  <td>
    <div class="col-md-12 text-center">
      <%= link_to "Show", laptop, method: :get, class: 'btn btn-info text-white '%>
    </div>
  </td>
</tr>

app/views/laptops/edit.html.erb
<h1>Editing laptop</h1>

<%= render "form", laptop: @laptop %>

<br>

<div>
  <%= link_to "Show this laptop", @laptop %> |
  <%= link_to "Back to laptops", laptops_path %>
</div>

app/views/laptops/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-sm">
      <h1>Laptops</h1>
    </div>
    <div class="col-sm d-flex flex-row-reverse p-2">
      <%= link_to "New laptop", new_laptop_path, method: :get, class: 'btn btn-info text-white'%>
    </div>
  </div>
</div>
<br/>
<div id="laptops">
  <table class="table table-striped-columns table-bordered table-hover">
    <thead class="table-dark">
      <tr>
        <th scope="col">Brand</th>
        <th scope="col">Model</th>
        <th scope="col">Price</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @laptops.each do |laptop| %>
        <%= render laptop %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/laptops/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm">
      <h1>New laptop</h1>
    </div>
    <div class="col-sm d-flex flex-row-reverse p-2">
      <%= link_to "Back to laptops", laptops_path, method: :get, class: 'btn btn-secondary '%>
    </div>
  </div>
</div>
<br/>
<%= render "form", laptop: @laptop %>

app/views/laptops/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="jumbotron">
  <h1 class="display-4">
    <%= @laptop.brand %>   <%= @laptop.model %>  
  </h1>
  <p class="lead">     
    <%= @laptop.price %>  PLN
  </p>
</div>
<br/>
<div>
  <%= link_to "Edit this laptop", edit_laptop_path(@laptop), class: "btn btn-secondary" %>  
  <%= link_to "Back to laptops", laptops_path, class: "btn btn-secondary" %>
  <br/>
  <br/>
  <%= button_to "Destroy this laptop", @laptop, method: :delete, class: "btn btn-danger"  %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Techmarket App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
  <body>
      <%= render 'home/header' %>
    <div class="container">
      <br/>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>